### ISSUE TITLE
api_token

### ISSUE THREAD

**Issue by azfirefighter** [criscola/cloudflare-ddns#1]
I keep getting an "invalid credentials: API Token must not be empty" error.   In my .cloudflare-ddns/config.yaml, I tried just using my Zone ID entered under zone_id and that didn't work.  The example config file doesn't have an example api_token entry, so I created an entry and pasted my global API key into THAT spot and I'm still getting the area.  Exactly which of the three API keys that I have from cloudflare is the one I'm supposed to use and that is the config entry for it?

**Comment by criscola** [comment]
Hi! Thank you very much for opening an issue. You are totally right, the existing example config was incomplete. I have pushed an updated config (also fixed the relative Helm chart in case someone wants to deploy the service on Kubernetes).
To answer the other questions about API keys/Zone id, please consult the following documentation: 
- https://developers.cloudflare.com/fundamentals/get-started/basic-tasks/find-account-and-zone-ids/
- https://developers.cloudflare.com/api/tokens/create/ -- make sure to select the desired zone and give Edit permissions to the api token
Feel free to post additional issues in case you run into further problems. Cheers.
